// iOS build stub — normally generated by PCSX2 build system
#pragma once
#define GIT_TAG "v2.7.340"
#define GIT_TAGGED_COMMIT true
#define GIT_TAG_HI 2
#define GIT_TAG_MID 7
#define GIT_TAG_LO 340
#define GIT_REV "v2.7.340"
#define GIT_HASH "c1cb214"
#define GIT_DATE "2026-05-14"
