#ifndef HAD_CONFIG_H
#define HAD_CONFIG_H
#include "zipconf.h"
#define HAVE_STDBOOL_H 1
#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STRDUP 1
#define HAVE_STRCASECMP 1
#define HAVE_STRNCASECMP 1
#define HAVE_FTELLO 1
#define HAVE_FSEEKO 1
#define HAVE_MKSTEMP 1
#define HAVE_SNPRINTF 1
#define HAVE_LOCALTIME_R 1
#define HAVE_FILENO 1
#define HAVE_FDOPEN 1
#define HAVE_SETMODE 1
#define HAVE_OPEN 1
#define HAVE_CLOSE 1
#define HAVE_READ 1
#define HAVE_WRITE 1
#define HAVE_STRTOLL 1
#define HAVE_STRTOULL 1
#define HAVE_STRERROR 1
#define HAVE_STRICMP 1
#define HAVE_STRERROR_R 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_GETRANDOM 1
#define HAVE_ARC4RANDOM 1
#define HAVE_ARC4RANDOM_BUF 1
#define HAVE_GMTIME_R 1
#define HAVE__GMTIME64_S 0
#define HAVE_STRUCT_TM_TM_ZONE 1
#define HAVE_SSIZE_T 1
#define HAVE_VISIBILITY 1
#endif
